{
 "title": "Mastering Apache Cassandra",
 "tags": [ "cassandra" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "env",
    "query": "show tag values from /cpu/ with key=\"env\";"
   },
   {
    "name": "app",
    "query": "show tag values from /cpu/ with key=\"app\" where \"env\" = '$env';"
   },
   {
    "name": "region",
    "query": "show tag values from /cpu/ with key=\"region\" where \"app\" = '$app' and \"env\" = '$env';"
   }
  ]
 },
 "panels": [
  { "title": "cpu-# of down nodes-heap mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "# of Down Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "FailureDetector",
     "select": [
      [
       { "params": [ "DownEndpointCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap Mem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "Memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "avg throughput and latency-hints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Total Avg reads/second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ClientRequest",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " /3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
      { "condition": "AND", "key": "Read", "operator": "=", "value": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "P99 Avg Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ClientRequest",
     "select": [
      [
       { "params": [ "99thPercentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
      { "condition": "AND", "key": "Read", "operator": "=", "value": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "Hints Inprogress",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "Storage",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "P99 Avg Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ClientRequest",
     "select": [
      [
       { "params": [ "99thPercentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
      { "condition": "AND", "key": "Write", "operator": "=", "value": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "Total Avg writes/second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ClientRequest",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " /3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
      { "condition": "AND", "key": "Write", "operator": "=", "value": "Latency" }
     ]
    }
   ]
  },
  { "title": "throughput-# of down nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "reads/second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "ClientRequest",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
      { "condition": "AND", "key": "Read", "operator": "=", "value": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "# of Down Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "FailureDetector",
     "select": [
      [
       { "params": [ "DownEndpointCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "writes/second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "ClientRequest",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
      { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
      { "condition": "AND", "key": "Write", "operator": "=", "value": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read latency - P95",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ClientRequest",
       "select": [
        [
         { "params": [ "95thPercentile" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "Read", "operator": "=", "value": "Latency" }
       ]
      }
     ]
    },
    {
     "title": "Read latency - P99",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ClientRequest",
       "select": [
        [
         { "params": [ "99thPercentile" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "Read", "operator": "=", "value": "Latency" }
       ]
      }
     ]
    },
    {
     "title": "Write latency - P95",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ClientRequest",
       "select": [
        [
         { "params": [ "95thPercentile" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "Write", "operator": "=", "value": "Latency" }
       ]
      }
     ]
    },
    {
     "title": "Write latency - P99",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ClientRequest",
       "select": [
        [
         { "params": [ "99thPercentile" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "Write", "operator": "=", "value": "Latency" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "network in and out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Net Bytes In",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "Net Bytes Out",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "Net Errors In",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "Net Errors Out",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "cassandra internals (timeouts, reapirs, data size, open tcp connections, load, compactions)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Timeouts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ClientRequest",
       "select": [
        [
         { "params": [ "OneMinuteRate" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "Read", "operator": "=", "value": "Timeouts" }
       ]
      }
     ]
    },
    {
     "title": "Write Timeouts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ClientRequest",
       "select": [
        [
         { "params": [ "OneMinuteRate" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "Write", "operator": "=", "value": "Timeouts" }
       ]
      }
     ]
    },
    {
     "title": "Connection Timeouts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "Client",
       "select": [
        [
         { "params": [ "Value" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "Open TCP connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_currestab" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "Active Repairs",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ThreadPools",
       "select": [
        [
         { "params": [ "Value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "ReadRepairStage", "operator": "=", "value": "ActiveTasks" }
       ]
      }
     ]
    },
    {
     "title": "Pending Repairs",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ThreadPools",
       "select": [
        [
         { "params": [ "Value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "ReadRepairStage", "operator": "=", "value": "PendingTasks" }
       ]
      }
     ]
    },
    {
     "title": "Data Size",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "path", "operator": "=", "value": "/usr/lib/cassandra/data" }
       ]
      }
     ]
    },
    {
     "title": "1m Load",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "compactions/minute",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "Compaction",
       "select": [
        [
         { "params": [ "OneMinuteRate" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "TotalCompactionsCompleted", "operator": "=", "value": "Count" }
       ]
      }
     ]
    },
    {
     "title": "Pending Compaction Tasks",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "Compaction",
       "select": [
        [
         { "params": [ "Value" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" },
        { "condition": "AND", "key": "PendingTasks", "operator": "=", "value": "Value" }
       ]
      }
     ]
    },
    {
     "title": "disk read iops",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    },
    {
     "title": "disk write iops",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$app$/" },
        { "condition": "AND", "key": "region", "operator": "=~", "value": "/^$region$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}